# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_index=True, max_length=250)),
                ('code', models.CharField(db_index=True, max_length=15)),
                ('isbn', models.CharField(db_index=True, max_length=30)),
                ('article', models.CharField(max_length=15)),
                ('year', models.IntegerField(default=0)),
                ('tema', models.CharField(db_index=True, max_length=100)),
                ('serya', models.CharField(db_index=True, max_length=300)),
                ('age', models.IntegerField(default=0)),
                ('authors', models.CharField(db_index=True, max_length=300)),
                ('listeditors', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('cover', models.CharField(max_length=30)),
                ('pages', models.IntegerField(default=0)),
                ('superobl', models.BooleanField()),
                ('volnodiv', models.BooleanField()),
                ('size_x', models.IntegerField(default=0)),
                ('size_y', models.IntegerField(default=0)),
                ('size_z', models.IntegerField(default=0)),
                ('format', models.CharField(max_length=20)),
                ('weigth', models.IntegerField(default=0)),
                ('prim', models.TextField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desc.Products'),
        ),
        migrations.AddField(
            model_name='barcodes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desc.Products'),
        ),
    ]
