# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desc', '0002_auto_20160401_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['fullname']},
        ),
        migrations.AddField(
            model_name='prices',
            name='shop_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prices',
            name='shop_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='decor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='paper_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sex',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='barcodes',
            name='barcode',
            field=models.CharField(db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='authors',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='cover',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='fullname',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='isbn',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='listeditors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='serya',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='tema',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
