# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desc', '0004_auto_20160425_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prim',
            field=models.TextField(blank=True),
        ),
    ]
