# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desc', '0005_auto_20160425_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='guid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
